### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/mariadb#1]
mariadb is missing some perl deps:

package: 3:mariadb-bench-10.1.21-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     perl(DBI)
     perl(GD)
package: 3:mariadb-server-galera-10.1.21-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     galera >= 0:25.3.3
package: 3:mariadb-server-utils-10.1.21-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     perl(DBD::mysql)
     perl(DBI)

**Comment by contyk** [comment]
`mariadb-bench` could probably be safely removed. You'll still need to include deps to satisfy the rest, however.

**Comment by r4f4** [comment]
mariadb should not include gettext. Eventually it will end up pulling in emacs.
base-runtime should provide everything any gettext user needs.

**Comment by r4f4** [comment]
mariadb includes libselinux wich pulls in libselinux-ruby, requiring ruby. libselinux is already included in base-runtime, so I don't think it needs to be listed in mariadb.

**Comment by r4f4** [comment]
package: policycoreutils-gui-2.6-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     gnome-python2
     gnome-python2-canvas
     gnome-python2-gnome
     pygtk2
     pygtk2-libglade
     python-slip-dbus
     usermode-gtk
package: policycoreutils-python-2.6-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     audit-libs-python >= 0:2.1.3-4
     libsemanage-python >= 0:2.6-0
package: policycoreutils-python3-2.6-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     audit-libs-python3 >= 0:2.1.3-4
package: policycoreutils-python3-2.6-5.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     audit-libs-python3 >= 0:2.1.3-4
package: policycoreutils-sandbox-2.6-5.module_b559d5e4.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     /usr/bin/xmodmap
     openbox
     xorg-x11-server-Xephyr >= 0:1.14.1-2

---
Notice that policycoreutils is already included by shared-userspace, so I guess it shouldn't be listed by mariadb.

**Comment by r4f4** [comment]
selinux-policy is already added to shared-userspace, so it can be dropped from mariadb.

**Comment by mkocka** [comment]
I removed selinux-policy and systemtap and I am going to submit it to mbs asap.

**Comment by mkocka** [comment]
build ID 654, if that builds and works I am going to close this issue

**Comment by mkocka** [comment]
already fixed, I am closing this.

**Comment by r4f4** [comment]
What about policycoreutils which is already included by shared-userspace?

**Comment by r4f4** [comment]
Also, I'm still seeing the following issues:

package: 3:mariadb-bench-10.1.21-5.module_8c332746.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     perl(DBI)
     perl(GD)
package: 3:mariadb-server-galera-10.1.21-5.module_8c332746.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     galera >= 0:25.3.3
package: 3:mariadb-server-utils-10.1.21-5.module_8c332746.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     perl(DBD::mysql)
     perl(DBI)

**Comment by mkocka** [comment]
Sorry for policycoreutils, I removed that now from MariaDB.

**Comment by mkocka** [comment]
I have no idea what to do with:
""" 
package: 3:mariadb-bench-10.1.21-5.module_8c332746.x86_64 from repoclosure-Server.x86_64
unresolved deps:
perl(DBI)
perl(GD)
package: 3:mariadb-server-galera-10.1.21-5.module_8c332746.x86_64 from repoclosure-Server.x86_64
unresolved deps:
galera >= 0:25.3.3
package: 3:mariadb-server-utils-10.1.21-5.module_8c332746.x86_64 from repoclosure-Server.x86_64
unresolved deps:
perl(DBD::mysql)
perl(DBI)
"""
Any ideas?

**Comment by r4f4** [comment]
According to @contyk, mariadb-bench can be filtered out. For the others, you should add the satisfying deps.
mariadb-server-galera: galera, boost-program-options, nmap-ncat, libpcap
mariadb-server-utils: perl-DBD-MySQL, perl-DBI.

**Comment by mkocka** [comment]
So this is what I am going to do, please correct me If it is wrong: 
 * filtering out mariadb-bench
 * adding these packages to components: 
 ** galera, boost-program-options, nmap-ncat, libpcap, perl-DBD-MySQL, perl-DBI 

Is that correct or I understand it wrong? Sorry I am a bit confused ...

**Comment by mkocka** [comment]
filter:
        rpms:   
                - mariadb-bench
                - mariadb-server-galera
                - mariadb-server-utils

in mbs with "id": 679
I hope it will works ;)

**Comment by r4f4** [comment]
fingers crossed
