### ISSUE TITLE
Duplicate dependencies

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/mariadb#3]
mariadb includes some packages which are already part of base-runtime or shared-userspace:
`checkpolicy`
`compat-openssl10`
`libaio`
`libedit`
`time`

**Comment by mkocka** [comment]
I removed all of them, but I am pretty sure that they use not to be part of  base-runtime or shared-userspace before. 
id: 700

**Comment by r4f4** [comment]
Yes, there has been changes to these other modules. I'm going to talk to the other guys if we can add some tests to check_modulemd so that the dev is notified of possible duplicate packages. Otherwise it's too cumbersome for the devs to know, since they would need to go through the changes in the included modules.

**Comment by mkocka** [comment]
True, it could be part of MBS, like the first check.

**Comment by nphilipp** [comment]
@mkocka has fixed this meanwhile.
